<<<<<<< HEAD
# Generated by Django 5.2 on 2025-10-08 10:40
=======
# Generated by Django 5.2 on 2025-10-08 07:28
>>>>>>> 627a7e8c5a5cabd1f625583a33cf8d889abe19d7

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_This_Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'About Organisation',
                'verbose_name_plural': 'About Organisation',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('adults', models.PositiveIntegerField(verbose_name='Number of Adults')),
                ('children', models.PositiveIntegerField(blank=True, verbose_name='Number of Children')),
                ('interested_in', models.CharField(blank=True, max_length=255, verbose_name='Interested In')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampingSafaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tour_title', models.CharField(max_length=500)),
                ('Tour_Descriptions', models.TextField()),
                ('Tour_price', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tanzania Camping Safaris',
                'verbose_name_plural': 'Tanzania Camping Safaris',
                'ordering': ['Tour_title'],
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'company',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Explore_zanzibar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tour_title', models.CharField(max_length=500)),
                ('Tour_Descriptions', models.TextField()),
                ('Tour_price', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Explore zanzibar',
                'verbose_name_plural': 'Explore zanzibar',
                'ordering': ['Tour_title'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Swali')),
                ('answer', models.TextField(verbose_name='Jibu')),
            ],
            options={
                'verbose_name': 'Swali na Jibu',
                'verbose_name_plural': 'Maswali na Majibu',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_headline', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoneymoonSafaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tour_title', models.CharField(max_length=500)),
                ('Tour_Descriptions', models.TextField()),
                ('Tour_price', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'SHoneymoon Safaris',
                'verbose_name_plural': 'Honeymoon Safaris',
                'ordering': ['Tour_title'],
            },
        ),
        migrations.CreateModel(
            name='Kilimanjaro_climbing_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=100)),
                ('image_1', models.CharField(blank=True, max_length=255, null=True)),
                ('title_2', models.CharField(max_length=100)),
                ('image_2', models.CharField(blank=True, max_length=255, null=True)),
                ('title_3', models.CharField(max_length=100)),
                ('image_3', models.CharField(blank=True, max_length=255, null=True)),
                ('title_4', models.CharField(max_length=100)),
                ('image_4', models.CharField(blank=True, max_length=255, null=True)),
                ('title_5', models.CharField(max_length=100)),
                ('image_5', models.CharField(blank=True, max_length=255, null=True)),
                ('title_6', models.CharField(max_length=100)),
                ('image_6', models.CharField(blank=True, max_length=255, null=True)),
                ('title_7', models.CharField(max_length=100)),
                ('image_7', models.CharField(blank=True, max_length=255, null=True)),
                ('title_8', models.CharField(max_length=100)),
                ('image_8', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serengeti_migration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tour_title', models.CharField(max_length=500)),
                ('Tour_Descriptions', models.TextField()),
                ('Tour_price', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Serengeti Migration',
                'verbose_name_plural': 'Serengeti Migrations',
                'ordering': ['Tour_title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step_for_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Step to Book',
                'verbose_name_plural': 'Steps to book',
                'ordering': ['Title'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.TextField()),
                ('facebook_link', models.URLField(blank=True, max_length=300, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=300, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('overview', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('featured_image', models.CharField(blank=True, max_length=255, null=True)),
                ('tour_type', models.CharField(choices=[('Beach', 'Beach'), ('Hiking', 'Hiking'), ('Safari', 'Safari'), ('Cultural', 'Cultural'), ('Kilimanjaro', 'Kilimanjaro')], default='Safari', max_length=100)),
            ],
            options={
                'verbose_name': 'Trekking',
                'verbose_name_plural': 'Trekkings',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('overview', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('featured_image', models.CharField(blank=True, max_length=255, null=True)),
                ('safari_type', models.CharField(default='Safari', max_length=100)),
            ],
            options={
                'verbose_name': 'Safari',
                'verbose_name_plural': 'Safaris',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Travels_Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('Offer_in_percent', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('is_unesco_site', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('overview', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('featured_image', models.CharField(blank=True, max_length=255, null=True)),
                ('trip_type', models.CharField(default='Safari', max_length=100)),
            ],
            options={
                'verbose_name': 'Day Trip',
                'verbose_name_plural': 'Day Trips',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User_Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('page_visited', models.URLField()),
            ],
            options={
                'verbose_name': 'User Visit',
                'verbose_name_plural': 'User Visits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Welcome_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('image_1', models.CharField(blank=True, max_length=255, null=True)),
                ('image_2', models.CharField(blank=True, max_length=255, null=True)),
                ('image_3', models.CharField(blank=True, max_length=255, null=True)),
                ('image_4', models.CharField(blank=True, max_length=255, null=True)),
                ('image_5', models.CharField(blank=True, max_length=255, null=True)),
                ('image_6', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camping_Itiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Camping_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itiner', to='travello.campingsafaris')),
            ],
            options={
                'verbose_name': 'Camping Itinenary',
                'verbose_name_plural': 'Camping Itinenary',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Honeymoon_Itiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Honeymoon_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itiner', to='travello.honeymoonsafaris')),
            ],
            options={
                'verbose_name': 'Honeymoon Itinenary',
                'verbose_name_plural': 'Honeymoon Itinenary',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Serengeti_Itiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('serengeti_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itiner', to='travello.serengeti_migration')),
            ],
            options={
                'verbose_name': 'Serengeti Itinenary',
                'verbose_name_plural': 'Serengeti Itinenary',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tour_Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('elevation_start', models.CharField(blank=True, max_length=50, null=True)),
                ('elevation_end', models.CharField(blank=True, max_length=50, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('hiking_time', models.CharField(blank=True, max_length=50, null=True)),
                ('habitat', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='travello.tour')),
            ],
            options={
                'verbose_name': 'Trekking Itinerary',
                'verbose_name_plural': 'Trekking Itinenary',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Travel_Itiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('elevation_start', models.CharField(blank=True, max_length=50, null=True)),
                ('elevation_end', models.CharField(blank=True, max_length=50, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('hiking_time', models.CharField(blank=True, max_length=50, null=True)),
                ('habitat', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itiner', to='travello.travel')),
            ],
            options={
                'verbose_name': 'Safari Itinenary',
                'verbose_name_plural': 'Safari Itinenary',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Trip_Itinerary_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='travello.trip_db')),
            ],
            options={
                'verbose_name': 'Day Trip Itinerary',
                'verbose_name_plural': 'Day Trip Itenerary',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('activity_details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='travello.uservisit')),
            ],
        ),
        migrations.CreateModel(
            name='zanzibar_Itiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('zanzibar_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itiner', to='travello.explore_zanzibar')),
            ],
            options={
                'verbose_name': 'Zanzibar Itinenary',
                'verbose_name_plural': 'Zanzibar Itinenary',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TravelPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('item_type', models.CharField(choices=[('include', 'Included'), ('exclude', 'Excluded')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Include and Execlude',
                'verbose_name_plural': 'Include and Execludetions',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'item_type'], name='travello_tr_content_b57bc1_idx')],
            },
        ),
    ]
