# Generated by Django 5.2 on 2025-10-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_this_organization',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about_this_organization',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about_this_organization',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about_this_organization',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
