# Generated by Django 5.2 on 2025-10-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_alter_about_this_organization_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcome_text',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='welcome_text',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
